/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Text,
});
export const Service = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const CompanyInfo = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'contactEmail' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getCompanyInfo' : IDL.Func([], [CompanyInfo], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getService' : IDL.Func([IDL.Text], [Service], ['query']),
  'initialize' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Text,
  });
  const Service = IDL.Record({ 'title' : IDL.Text, 'description' : IDL.Text });
  const CompanyInfo = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'contactEmail' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getCompanyInfo' : IDL.Func([], [CompanyInfo], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getService' : IDL.Func([IDL.Text], [Service], ['query']),
    'initialize' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };